// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbvRvBA17zE3-YYAUgpat6sHU8ZwB0lwc',
    appId: '1:910741702191:web:a78780e1ba5a8538d328da',
    messagingSenderId: '910741702191',
    projectId: 'live-score-app-8421f',
    authDomain: 'live-score-app-8421f.firebaseapp.com',
    storageBucket: 'live-score-app-8421f.firebasestorage.app',
    measurementId: 'G-RT6HEZ95HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwTGBUkOL0BoXeGg4I_IBLooeF2I8XWuM',
    appId: '1:910741702191:android:470ec0decdfc988fd328da',
    messagingSenderId: '910741702191',
    projectId: 'live-score-app-8421f',
    storageBucket: 'live-score-app-8421f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEw3Wn0PhNJSYa_tw07mvALJlD4ljLI_w',
    appId: '1:910741702191:ios:42e1d803e6f7afead328da',
    messagingSenderId: '910741702191',
    projectId: 'live-score-app-8421f',
    storageBucket: 'live-score-app-8421f.firebasestorage.app',
    iosBundleId: 'com.example.liveScoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEw3Wn0PhNJSYa_tw07mvALJlD4ljLI_w',
    appId: '1:910741702191:ios:42e1d803e6f7afead328da',
    messagingSenderId: '910741702191',
    projectId: 'live-score-app-8421f',
    storageBucket: 'live-score-app-8421f.firebasestorage.app',
    iosBundleId: 'com.example.liveScoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbvRvBA17zE3-YYAUgpat6sHU8ZwB0lwc',
    appId: '1:910741702191:web:e2bb880d2d9f22ddd328da',
    messagingSenderId: '910741702191',
    projectId: 'live-score-app-8421f',
    authDomain: 'live-score-app-8421f.firebaseapp.com',
    storageBucket: 'live-score-app-8421f.firebasestorage.app',
    measurementId: 'G-ELMSG3H6XL',
  );
}
